# 插件配置
server-name: "Aurora Field"  # 服务器名

# 消息同步部分
message-sync: false  # 此项设为false开启消息同步
qn: 0  #要同步过去的群号
uuid: ""  # 机器人UUID
message-report-url: "https://qqbot.xzy.center/1000"  # 上报地址，一般情况下无需更改

# say指令前缀
say-prefix: "[Q群消息]"

# 登录部分
login-verify: true  # 是否开启登录密码
login-success-msg: "登陆成功！"  # 登录成功时提示
login-fail-msg: "密码错误！"  # 登录失败时提示
reg-success-msg: "注册成功！"  # 注册成功时提示
reg-ip-count: 1  # 每个IP允许注册的账号数，0为不限制
reg-ip-max-fail-msg: "当前IP注册ID数量已达上限！"  # 当IP注册数量超的时候提示的内容
login-allow-tick: 600  # 指定tick后还未登录就踢出玩家
login-allow-tick-msg: "登录已超时，请重新进入"  # 登录超时时提示的消息
reg-allow-tick: 1200  # 指定tick后还未注册就踢出玩家
reg-allow-tick-msg: "注册已超时，请重新进入"  # 注册超时时提示的消息