server-name: "Aurora Field"  # 服务器名

# 消息同步部分
qn: 0  #要同步过去的群名
uuid: ""  # 机器人UUID
message-report-url: "https://qqbot.xzy.center/1000"  # 上报地址，一般情况下无需更改

# say指令前缀
say-prefix: "[Q群消息]"

# 登录部分
login-verify: true  # 是否开启登录密码
login-success-msg: "登陆成功！"  # 登录成功时提示
login-fail-msg: "密码错误！"  # 登录失败时提示
reg-success-msg: "注册成功！"  # 注册成功时提示
reg-ip-count: 1  # 每个IP允许注册的账号数
reg-ip-max-fail-msg: "当前IP注册ID数量已达上限！"  # 当IP注册数量超的时候提示的内容