name: MessageSync
version: '${project.version}'
main: center.xzy.qb.messagesync.Main
api-version: 1.13
authors: [xzyStudio]
description: Message Sync Plugin for PigBotFramework
website: https://qb.xzy.center
commands:
  ms:
    description: MessageSync消息同步相关指令
    usage: /ms
  say:
    description: 发送消息
    usage: /say <MessageContent>
permissions:
  messagesync.ms.*:
    description: Allows ms command
    default: op