name: MessageSync
version: '${project.version}'
main: center.xzy.qb.messagesync.Main
api-version: 1.19
authors: [xzyStudio]
description: Message Sync Plugin for PigBotFramework
website: https://qb.xzy.center
