name: MessageSync
version: '${project.version}'
main: center.xzy.qb.messagesync.Main
api-version: 1.13
authors: [xzyStudio]
soft-depend: [TitleManager]
description: Awesome Toolkit Plugin
website: https://xzynb.top
commands:
  ms:
    description: MessageSync消息同步相关指令
    usage: /ms
  say:
    description: 发送消息
    usage: /say <MessageContent>
permissions:
  messagesync.ms.say:
    description: Say Command
    default: true
  messagesync.ms.login:
    description: Login Command
    default: true
  messagesync.ms.*:
    description: All ms command
    default: op